### ISSUE TITLE
Import Eleves

### ISSUE THREAD

**Issue by MFaideau** [bLandais/projet-notes#49]
- Importer une liste d'élèves à partir d'un fichier CSV 
- ~~Importer une liste de visiteurs à partir d'un fichier CSV~~

**Comment by bLandais** [comment]
Liste de visiteurs, c'est pas à faire manuellement ça ?

**Comment by bLandais** [comment]
Il reste encore un bug (vérifier que l'utilisateur n'existe pas déjà)

**Comment by bLandais** [comment]
Ok pour la vérification de l'utilisateur. Reste un petit bug (accent à gérer)

**Comment by bLandais** [comment]
OK pour les accents. Je ferme le ticket.
